### ISSUE TITLE
Other speakers section

### ISSUE THREAD

**Issue by andresburns** [andresburns/javascript-week#4]
Other speakers section, featuring cards for every speaker, each card should open a lightbox modal when clicked, showing the speaker’s bio 

![image](https://user-images.githubusercontent.com/6728576/61905939-e1c96600-aeef-11e9-913d-36db79b2fdef.png)

**Comment by xkill-9** [comment]
Voy a tomar esta por la tarde entonces.

**Comment by xkill-9** [comment]
Solucionada en #12
